### ISSUE TITLE
Can't build on quicklisp build system

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/colleen#17]
Log is here: http://report.quicklisp.org/2015-08-03/failure-report/colleen.html#colleen

**Comment by Shinmera** [comment]
Unfortunately I can't reproduce the issue. The last file I'm seeing in the stack trace (`command-handler`) also hasn't been changed since the last quicklisp release, so I'm not sure what's going on there.

**Comment by quicklisp** [comment]
I think it's the same Verbose issue with different clothes due to an updated version of SBCL.

**Comment by Shinmera** [comment]
That doesn't make much sense since Verbose is an explicit dependency for Colleen.

**Comment by Shinmera** [comment]
Alright, I updated everything to the latest now and I can reproduce it. Sorry for all the noise, I'll see that I can fix it asap.

**Comment by Shinmera** [comment]
Looks like you were indeed right! I'm not quite sure how this escaped my testing. Sorry about that!

**Comment by quicklisp** [comment]
Can this fix be applied to qtools as well?

**Comment by Shinmera** [comment]
It should already be, since it was a change to Verbose itself, so anything that might have previously been affected should be working fine now.
